default:
  tags:
    - CREMI 
    - Bookworm

stages:
  - build
  - test
  - coverage

build-job1:
  stage: build
  script:
    - python3 -m pip install --break-system-packages coverage

test-job1:
  stage: test
  script:
    - python3 -m unittest discover -v tests

coverage-job1:
  stage: coverage
  script :
    - python3 -m coverage run -m unittest discover tests
    - python3 -m coverage report --ignore-errors -m